version: 1.2
  workflows:
    - subclass: WDL
      primaryDescriptorPath: /vrs-annotator/vrs-annotator.wdl
      readMePath: /vrs-annotator/README.md
      authors:
        - name: Quinn Wai Wong
          email: wongq@ohsu.edu